### ISSUE TITLE
D2 Project Decomp.

### ISSUE THREAD

**Issue by horinet** [Berea-CS-Courses/capstone-project-horinet#6]

**Comment by belainehi** [comment]
Great breakdown of the scope of your application. A more detailed breakdown of the technical requirements (Functional requirements describe the functionality or capability that the software is to have and thus describes how it works, as opposed to why or even what it does.) of the app like how the app allows users to input new appointments or sends out reminders would be helpful in the design process.  Defining the non-technical requirements (qualities or constraints that the software must have or comply with, but which are not operations that will be automated) like where you will host your application was also part of the assignment requirement.

**Comment by smanalai** [comment]
You have identified the components of your application. However, I would suggest digging deeper and come up with even smaller components for the app. This will help you in prioritizing which component is the most essential for a basic working app. In most cases, starting with the front-end component makes sense and then you can build the backend and connect them together so that you have a fully working application. I did not see a database component for your application but it might be because you don't want to save user information. However, if you decide to save user information you can look into some databases such as MongoDB or PostgreSQL. Overall, you have done a good job. My last suggestion is to create a hierarchy of the components so you know which components you should start working on first.
