### ISSUE TITLE
D3: Low-Fi prototype

### ISSUE THREAD

**Issue by horinet** [Berea-CS-Courses/capstone-project-horinet#8]
Complete Low-Fi prototype. Draft due 3-10, final due 3-17. This is a low-fi prototype of my application. I am doing both a paper prototype and a prototype on excalidraw for the rough draft.

**Comment by jazzij** [comment]
Very nice digital sketches on excalidraw 👍 

Looking forward to seeing the paper prototype and the user flow diagrams. You might want to do user flows before the paper prototype in case you decide do to make changes to the sketches.

**Comment by smanalai** [comment]
Good job on your UI sketches. I like how you have created multiple slides for each of your application pages and components. I think it is well designed and will definitely be helpful once you want to create those components. As for your model diagram, I think that a user flow diagram is a great choice for your application since it will show you how a person would interact with your system. Also, I suggest that trying the entity-relationship diagram might also be helpful for you because it will give you a visual representation of the user data that you might have to store in your databases such as their schedules, free times, and etc.
